# Generated by Django 4.0.6 on 2022-07-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognition', '0002_rename_emp_image_fileuploaded_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploaded',
            name='title',
        ),
        migrations.AddField(
            model_name='fileuploaded',
            name='model',
            field=models.CharField(choices=[('1', 'VGG16'), ('2', 'VGG19'), ('3', 'DENSENET')], default='1', max_length=2),
        ),
    ]
