# Generated by Django 4.0.6 on 2022-07-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognition', '0003_remove_fileuploaded_title_fileuploaded_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploaded',
            name='model',
        ),
        migrations.AlterField(
            model_name='fileuploaded',
            name='image',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
